/* Copyright Statement:
*This firmware are protected under relevant copyright laws,this information contained
*herein is confidential and proprietary to Goodix.
*
*GOODIX (C) 2013. All rights reserved.
*
*WARNING:The GTP_COMPATIBLE_MODE part of this file was generated by the specialized tools,
*please do not modify it manually!
*
*/


#ifndef _GT9XX_FIRMWARE_H_
#define _GT9XX_FIRMWARE_H_

#if GTP_HEADER_FW_UPDATE
unsigned char gtp_default_FW[] = 
{
            //TODO:Puts your update firmware data  here!
};

#endif

/*
*[HW INFO]00900600
*[PID]910
*[VID]1010
*[GENERATED]2013/08/27 20:59:13
*/
#if GTP_COMPATIBLE_MODE
//sensor ID == 0
unsigned char gtp_fw_fl_sensor0[] = 
{
#include "s520x_dijing_1041.txt"
};
//sensor ID == 1
unsigned char gtp_fw_fl_sensor1[] = 
{
#include "s520x_shenyue_1040.txt"
};
// sensor ID == 2
unsigned char gtp_fw_fl_sensor2[] = 
{
#include "s520x_jtouch_1041.txt"
};

// default fw
unsigned char gtp_default_FW_fl[] = 
{
#include "s520x_default_fw.txt"
};
#endif

#endif
